### ISSUE TITLE
[feedback] - Suggested friends as new tab in /members page and add widget

### ISSUE THREAD

**Issue by ghost** [hypeJunction/hypeMatchmaker#2]
Just another feedback :)
I needed a while to find the page with suggested friends. Imo the plugin should create a new tab in /members page and add a widget to use in profile and dashboard, pretty Elgg standarda I guess.
Cheers

**Comment by hypeJunction** [comment]
Isn't there a tab on the friends page?

**Comment by ghost** [comment]
Not for me (maybe theme?)
There would be even better actually

**Comment by hypeJunction** [comment]
Some day.... When there is free time. I don't currently use this for anything
